services:
  web:
    image: gemini-analyzer
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=5000
      - DEBUG=False
      - MAX_REQUESTS_PER_HOUR=1000
      - RATE_LIMIT_WINDOW=3600
      - MAX_CONTENT_LENGTH=16777216
      - ALLOWED_EXTENSIONS=png,jpg,jpeg,gif,webp,mp4,webm,ogg
      - CORS_ORIGINS=http://localhost:5000,https://yourdomain.com
      - LOG_LEVEL=INFO
      - LOG_FILE=gemini_analyzer.log
    restart: always
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
